### PR TITLE
Don't skip build on Windows

### PR DESCRIPTION
**Pull request by erikbern**
Not really sure what I'm doing, but I'm testing a suggestion from here: https://github.com/spotify/annoy/issues/480#issuecomment-624193910

Checklist
* [X] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by erikbern** [comment]
Is the CI actually running on Windows? How do I know this works?

**Comment by erikbern** [comment]
Just saw this https://github.com/conda-forge/python-annoy-feedstock/commit/6046ee7f7e16c7c6ce6d1f86e05ee5e3ec4db096

Let me try to revert those changes as well

**Comment by erikbern** [comment]
Would appreciate some help here, I seriously have no idea what I'm doing

How do I enable windows builds in CI? (Travis?)

**Comment by pavlin-policar** [comment]
I suspect you haven't rerendered the feedstock since it's still running things on Travis. You can either do this locally (which is a pain) or leave a comment with the phrase

@conda-forge-admin, please rerender

and a bot will push a commit fixing up the CI config files here. Hopefully, this triggers the bot.

**Comment by xhochy** [comment]
@conda-forge-admin please rerender

**Comment by xhochy** [comment]
> I suspect you haven't rerendered the feedstock since it's still running things on Travis. You can either do this locally (which is a pain) or leave a comment with the phrase

Travis is ok as we use it for `ppc64le` builds.

**Comment by xhochy** [comment]
> This syntax is outdated since years, I'll push a new commit later with the correct syntax.

Things are simply nowadays, all that clutter can just be removed. Let's see how far we get with compiling.

**Comment by xhochy** [comment]
Happy Windowsing!

**Comment by pavlin-policar** [comment]
Awesome, thanks for the help!

**Comment by erikbern** [comment]
Thanks a lot, really awesome!

**Pull request merged**
